const schools = [
  { school: "Harvard University" },
  { school: "Stanford University" },
  { school: "Massachusetts Institute of Technology" },
  { school: "California Institute of Technology" },
  { school: "University of Oxford" },
  { school: "University of Cambridge" },
  { school: "University of Chicago" },
  { school: "Princeton University" },
  { school: "Columbia University" },
  { school: "Yale University" },
  { school: "University of California, Berkeley" },
  { school: "University of California, Los Angeles" },
  { school: "University of Pennsylvania" },
  { school: "Johns Hopkins University" },
  { school: "University of Michigan" },
  { school: "Cornell University" },
  { school: "Northwestern University" },
  { school: "New York University" },
  { school: "University of Toronto" },
  { school: "University College London" },
  { school: "Imperial College London" },
  { school: "Swiss Federal Institute of Technology Zurich" },
  { school: "National University of Singapore" },
  { school: "University of Sydney" },
  { school: "University of Melbourne" },
];

export default schools;
